// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/getting-started": {
    params: {};
  };
  "/guides/using-box": {
    params: {};
  };
  "/guides/using-annotation": {
    params: {};
  };
  "/guides/using-ansi": {
    params: {};
  };
  "/guides/using-layout": {
    params: {};
  };
  "/guides/common-patterns": {
    params: {};
  };
  "/api/box": {
    params: {};
  };
  "/api/annotation": {
    params: {};
  };
  "/api/ansi": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/getting-started" | "/guides/using-box" | "/guides/using-annotation" | "/guides/using-ansi" | "/guides/using-layout" | "/guides/common-patterns" | "/api/box" | "/api/annotation" | "/api/ansi";
  };
  "content/index.mdx": {
    id: "content/index";
    page: "/";
  };
  "content/getting-started.mdx": {
    id: "content/getting-started";
    page: "/getting-started";
  };
  "content/guides/using-box.mdx": {
    id: "content/guides/using-box";
    page: "/guides/using-box";
  };
  "content/guides/using-annotation.mdx": {
    id: "content/guides/using-annotation";
    page: "/guides/using-annotation";
  };
  "content/guides/using-ansi.mdx": {
    id: "content/guides/using-ansi";
    page: "/guides/using-ansi";
  };
  "content/guides/using-layout.mdx": {
    id: "content/guides/using-layout";
    page: "/guides/using-layout";
  };
  "content/guides/common-patterns.mdx": {
    id: "content/guides/common-patterns";
    page: "/guides/common-patterns";
  };
  "content/api/box.mdx": {
    id: "content/api/box";
    page: "/api/box";
  };
  "content/api/annotation.mdx": {
    id: "content/api/annotation";
    page: "/api/annotation";
  };
  "content/api/ansi.mdx": {
    id: "content/api/ansi";
    page: "/api/ansi";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "content/index": typeof import("./app/content/index.mdx");
  "content/getting-started": typeof import("./app/content/getting-started.mdx");
  "content/guides/using-box": typeof import("./app/content/guides/using-box.mdx");
  "content/guides/using-annotation": typeof import("./app/content/guides/using-annotation.mdx");
  "content/guides/using-ansi": typeof import("./app/content/guides/using-ansi.mdx");
  "content/guides/using-layout": typeof import("./app/content/guides/using-layout.mdx");
  "content/guides/common-patterns": typeof import("./app/content/guides/common-patterns.mdx");
  "content/api/box": typeof import("./app/content/api/box.mdx");
  "content/api/annotation": typeof import("./app/content/api/annotation.mdx");
  "content/api/ansi": typeof import("./app/content/api/ansi.mdx");
};